[build]

[[redirects]]
  from = "/azure-functions"
  to = "https://medium.com/hitachisolutions-braintrust/azure-functions-v2-dependency-injection-using-net-core-fccd93b80c0"
  status = 301
  force = false
  query = {path = ":path"}